<?php
/**
 * Private `hk9_submission` post type: stored form submissions with a read-only
 * admin view, list-table columns, and a daily retention cron.
 *
 * Meta (all private):
 *   _hk9_form (string) · _hk9_fields (array of sanitized values) · _hk9_mail_sent (bool)
 *   _hk9_ip_hash (daily-salted hash; never the IP) · _hk9_source_post (int) · _hk9_submitted_gmt (Y-m-d H:i:s)
 *
 * @package HK9\Core
 */

declare(strict_types=1);

namespace HK9\Core\Forms;

defined( 'ABSPATH' ) || exit;

final class Submissions {

	public const POST_TYPE = 'hk9_submission';
	public const CRON_HOOK = 'hk9_submissions_retention';

	/** Primitive caps generated by capability_type [hk9_submission, hk9_submissions]. */
	private const CAPS = [
		'edit_hk9_submission',
		'read_hk9_submission',
		'delete_hk9_submission',
		'edit_hk9_submissions',
		'edit_others_hk9_submissions',
		'publish_hk9_submissions',
		'read_private_hk9_submissions',
		'delete_hk9_submissions',
		'delete_private_hk9_submissions',
		'delete_published_hk9_submissions',
		'delete_others_hk9_submissions',
		'edit_private_hk9_submissions',
		'edit_published_hk9_submissions',
		'hk9_view_submissions',
	];

	private static bool $writing = false;

	public static function register(): void {
		add_action( 'init', [ self::class, 'register_post_type' ], 5 );
		add_filter( 'hk9/post_types/definitions', [ self::class, 'definition_override' ] );
		add_action( 'init', [ self::class, 'ensure_cron' ], 20 );
		add_action( self::CRON_HOOK, [ self::class, 'run_retention' ] );
		add_filter( 'user_has_cap', [ self::class, 'grant_admin_caps' ], 10, 4 );
		add_filter( 'wp_insert_post_data', [ self::class, 'enforce_read_only' ], 10, 2 );
		add_filter( 'wp_untrash_post_status', [ self::class, 'untrash_status' ], 10, 2 );

		if ( is_admin() ) {
			add_action( 'admin_menu', [ self::class, 'fallback_menu' ], 9 );
			add_action( 'add_meta_boxes_' . self::POST_TYPE, [ self::class, 'meta_boxes' ] );
			add_action( 'admin_enqueue_scripts', [ self::class, 'enqueue_admin_assets' ] );
			add_filter( 'manage_' . self::POST_TYPE . '_posts_columns', [ self::class, 'columns' ] );
			add_action( 'manage_' . self::POST_TYPE . '_posts_custom_column', [ self::class, 'column_content' ], 10, 2 );
			add_filter( 'post_row_actions', [ self::class, 'row_actions' ], 10, 2 );
			add_filter( 'bulk_actions-edit-' . self::POST_TYPE, [ self::class, 'bulk_actions' ] );
			add_action( 'restrict_manage_posts', [ self::class, 'filter_dropdown' ] );
			add_action( 'pre_get_posts', [ self::class, 'apply_filter' ] );
			add_filter( 'enter_title_here', [ self::class, 'title_placeholder' ], 10, 2 );
			add_filter( 'post_updated_messages', [ self::class, 'updated_messages' ] );
		}
	}

	public static function activate(): void {
		self::register_post_type();
		self::ensure_cron();
	}

	public static function deactivate(): void {
		wp_clear_scheduled_hook( self::CRON_HOOK );
	}

	/**
	 * When PostTypes\Registrar registers the CPTs it runs first at the same priority;
	 * this filter layers the form-owned definition (labels, export/user-deletion guards)
	 * over its entry so the effective registration is identical either way.
	 *
	 * @param array<string,array> $types type => register_post_type() args.
	 */
	public static function definition_override( array $types ): array {
		if ( isset( $types[ self::POST_TYPE ] ) && is_array( $types[ self::POST_TYPE ] ) ) {
			$types[ self::POST_TYPE ] = array_merge( $types[ self::POST_TYPE ], self::post_type_args() );
		}
		return $types;
	}

	public static function register_post_type(): void {
		if ( post_type_exists( self::POST_TYPE ) ) {
			return;
		}
		register_post_type( self::POST_TYPE, self::post_type_args() );
	}

	/** register_post_type() arguments (private, admin-only, read-only, not exportable). */
	private static function post_type_args(): array {
		return [
			'labels'              => [
				'name'               => __( 'Form Submissions', 'heartland-k9s-core' ),
				'singular_name'      => __( 'Form Submission', 'heartland-k9s-core' ),
				'menu_name'          => __( 'Submissions', 'heartland-k9s-core' ),
				'all_items'          => __( 'Submissions', 'heartland-k9s-core' ),
				'edit_item'          => __( 'View Submission', 'heartland-k9s-core' ),
				'view_item'          => __( 'View Submission', 'heartland-k9s-core' ),
				'search_items'       => __( 'Search submissions', 'heartland-k9s-core' ),
				'not_found'          => __( 'No submissions yet.', 'heartland-k9s-core' ),
				'not_found_in_trash' => __( 'No submissions in Trash.', 'heartland-k9s-core' ),
			],
			'description'         => __( 'Messages received through the contact and application inquiry forms.', 'heartland-k9s-core' ),
			'public'              => false,
			'publicly_queryable'  => false,
			'exclude_from_search' => true,
			'show_ui'             => true,
			'show_in_menu'        => 'hk9',
			'show_in_admin_bar'   => false,
			'show_in_nav_menus'   => false,
			'show_in_rest'        => false,
			'query_var'           => false,
			'rewrite'             => false,
			'can_export'          => false,
			'delete_with_user'    => false,
			'hierarchical'        => false,
			'supports'            => [ 'title' ],
			'capability_type'     => [ 'hk9_submission', 'hk9_submissions' ],
			'map_meta_cap'        => true,
			'capabilities'        => [
				'create_posts' => 'do_not_allow',
			],
		];
	}

	/** Administrators can always manage submissions, regardless of stored role caps. */
	public static function grant_admin_caps( array $allcaps, array $caps, array $args, \WP_User $user ): array {
		if ( empty( $allcaps['manage_options'] ) ) {
			return $allcaps;
		}
		foreach ( self::CAPS as $cap ) {
			$allcaps[ $cap ] = true;
		}
		return $allcaps;
	}

	/**
	 * Store a validated submission.
	 *
	 * @param array<string,mixed> $values  Validated values.
	 * @param array<string,mixed> $context {ip_hash, source_post, submitted_gmt}
	 * @return int Post id (0 on failure).
	 */
	public static function store( AbstractForm $form, array $values, array $context = [] ): int {
		$submitted_gmt = (string) ( $context['submitted_gmt'] ?? current_time( 'mysql', true ) );
		$title         = sprintf(
			/* translators: 1: form label, 2: date/time */
			__( '%1$s — %2$s', 'heartland-k9s-core' ),
			$form->label(),
			wp_date( get_option( 'date_format' ) . ' ' . get_option( 'time_format' ), strtotime( $submitted_gmt . ' UTC' ) ?: null )
		);
		// Searchable summary (name + email) so the admin search box finds submissions; never rendered publicly.
		$content = trim( $form->submitter_name( $values ) . ' ' . $form->submitter_email( $values ) );

		self::$writing = true;
		$id            = wp_insert_post(
			[
				'post_type'     => self::POST_TYPE,
				'post_status'   => 'publish',
				'post_title'    => $title,
				'post_content'  => $content,
				'post_author'   => 0,
				'post_date_gmt' => $submitted_gmt,
				'post_date'     => get_date_from_gmt( $submitted_gmt ),
				'meta_input'    => [
					'_hk9_form'          => $form->id(),
					'_hk9_fields'        => $values,
					'_hk9_mail_sent'     => 0,
					'_hk9_ip_hash'       => (string) ( $context['ip_hash'] ?? '' ),
					'_hk9_source_post'   => (int) ( $context['source_post'] ?? 0 ),
					'_hk9_submitted_gmt' => $submitted_gmt,
				],
			],
			false
		);
		self::$writing = false;

		return is_int( $id ) && $id > 0 ? $id : 0;
	}

	public static function record_mail( int $submission_id, bool $sent ): void {
		if ( $submission_id > 0 ) {
			update_post_meta( $submission_id, '_hk9_mail_sent', $sent ? 1 : 0 );
		}
	}

	/** Restored submissions go back to 'publish' (core would demote them to 'draft'). */
	public static function untrash_status( string $new_status, int $post_id ): string {
		return self::POST_TYPE === get_post_type( $post_id ) ? 'publish' : $new_status;
	}

	/** Prevent edits from the admin UI: only trash/untrash transitions may change a stored submission. */
	public static function enforce_read_only( array $data, array $postarr ): array {
		if ( self::$writing || self::POST_TYPE !== ( $data['post_type'] ?? '' ) ) {
			return $data;
		}
		$id = (int) ( $postarr['ID'] ?? 0 );
		if ( 0 === $id ) {
			return $data;
		}
		$current = get_post( $id );
		if ( ! $current instanceof \WP_Post ) {
			return $data;
		}
		$trashing   = 'trash' === ( $data['post_status'] ?? '' );
		$untrashing = 'trash' === $current->post_status;
		foreach ( [ 'post_title', 'post_content', 'post_excerpt', 'post_name', 'post_author', 'post_date', 'post_date_gmt', 'post_parent', 'menu_order' ] as $field ) {
			$data[ $field ] = $current->$field;
		}
		if ( ! $trashing && ! $untrashing ) {
			$data['post_status'] = $current->post_status;
		}
		return $data;
	}

	/* ---------------------------------------------------------------------
	 * Retention
	 * ------------------------------------------------------------------ */

	public static function ensure_cron(): void {
		if ( ! wp_next_scheduled( self::CRON_HOOK ) ) {
			wp_schedule_event( time() + HOUR_IN_SECONDS, 'daily', self::CRON_HOOK );
		}
	}

	/** Delete submissions older than `forms.retention_days` (0 = keep forever). Batched. */
	public static function run_retention(): int {
		$days = Config::retention_days();
		if ( $days <= 0 ) {
			return 0;
		}
		$before  = gmdate( 'Y-m-d H:i:s', time() - $days * DAY_IN_SECONDS );
		$deleted = 0;
		for ( $batch = 0; $batch < 20; $batch++ ) {
			$ids = get_posts(
				[
					'post_type'              => self::POST_TYPE,
					'post_status'            => 'any',
					'fields'                 => 'ids',
					'numberposts'            => 100,
					'no_found_rows'          => true,
					'update_post_meta_cache' => false,
					'update_post_term_cache' => false,
					'date_query'             => [
						[
							'column' => 'post_date_gmt',
							'before' => $before,
						],
					],
				]
			);
			if ( [] === $ids ) {
				break;
			}
			foreach ( $ids as $id ) {
				if ( wp_delete_post( (int) $id, true ) ) {
					$deleted++;
				}
			}
		}
		return $deleted;
	}

	/* ---------------------------------------------------------------------
	 * Admin
	 * ------------------------------------------------------------------ */

	/** Minimal "Heartland" top-level menu when the Admin\Menu module is absent (dev safety net). */
	public static function fallback_menu(): void {
		if ( class_exists( 'HK9\\Core\\Admin\\Menu' ) ) {
			return;
		}
		global $admin_page_hooks;
		if ( isset( $admin_page_hooks['hk9'] ) ) {
			return;
		}
		add_menu_page( __( 'Heartland', 'heartland-k9s-core' ), __( 'Heartland', 'heartland-k9s-core' ), 'edit_hk9_submissions', 'hk9', [ self::class, 'fallback_page' ], 'dashicons-pets', 25 );
	}

	public static function fallback_page(): void {
		echo '<div class="wrap"><h1>' . esc_html__( 'Heartland', 'heartland-k9s-core' ) . '</h1><p><a href="' . esc_url( admin_url( 'edit.php?post_type=' . self::POST_TYPE ) ) . '">' . esc_html__( 'Form Submissions', 'heartland-k9s-core' ) . '</a></p></div>';
	}

	public static function enqueue_admin_assets( string $hook ): void {
		$screen = function_exists( 'get_current_screen' ) ? get_current_screen() : null;
		if ( ! $screen || self::POST_TYPE !== $screen->post_type ) {
			return;
		}
		wp_enqueue_style( 'hk9-forms-admin', HK9_CORE_URL . 'assets/css/forms-admin.css', [], HK9_CORE_VERSION );
	}

	public static function meta_boxes( \WP_Post $post ): void {
		remove_meta_box( 'slugdiv', self::POST_TYPE, 'normal' );
		add_meta_box( 'hk9_submission_detail', __( 'Submission', 'heartland-k9s-core' ), [ self::class, 'render_detail' ], self::POST_TYPE, 'normal', 'high' );
		add_meta_box( 'hk9_submission_delivery', __( 'Delivery', 'heartland-k9s-core' ), [ self::class, 'render_delivery' ], self::POST_TYPE, 'side', 'high' );
	}

	/** Read-only field table (every value escaped; nothing editable). */
	public static function render_detail( \WP_Post $post ): void {
		$form_id = (string) get_post_meta( $post->ID, '_hk9_form', true );
		$form    = Handler::form( $form_id );
		$fields  = get_post_meta( $post->ID, '_hk9_fields', true );
		$fields  = is_array( $fields ) ? $fields : [];

		echo '<p class="hk9-submission__note">' . esc_html__( 'Submissions are read-only. Use Trash to remove this record.', 'heartland-k9s-core' ) . '</p>';
		echo '<table class="hk9-submission__table widefat striped"><tbody>';
		$definitions = $form ? $form->fields() : [];
		$keys        = array_unique( array_merge( array_keys( $definitions ), array_keys( $fields ) ) );
		foreach ( $keys as $key ) {
			if ( ! array_key_exists( $key, $fields ) ) {
				continue;
			}
			$label = (string) ( $definitions[ $key ]['label'] ?? $key );
			$value = $form ? $form->display_value( (string) $key, $fields[ $key ] ) : ( is_scalar( $fields[ $key ] ) ? (string) $fields[ $key ] : '' );
			$multi = 'textarea' === ( $definitions[ $key ]['type'] ?? '' );
			echo '<tr><th scope="row">' . esc_html( $label ) . '</th><td' . ( $multi ? ' class="hk9-submission__multiline"' : '' ) . '>';
			if ( 'email' === ( $definitions[ $key ]['type'] ?? '' ) && is_email( $value ) ) {
				echo '<a href="' . esc_url( 'mailto:' . $value ) . '">' . esc_html( $value ) . '</a>';
			} else {
				echo '' !== $value ? esc_html( $value ) : '&mdash;';
			}
			echo '</td></tr>';
		}
		echo '</tbody></table>';
	}

	public static function render_delivery( \WP_Post $post ): void {
		$form_id   = (string) get_post_meta( $post->ID, '_hk9_form', true );
		$form      = Handler::form( $form_id );
		$sent      = (bool) get_post_meta( $post->ID, '_hk9_mail_sent', true );
		$source    = (int) get_post_meta( $post->ID, '_hk9_source_post', true );
		$submitted = (string) get_post_meta( $post->ID, '_hk9_submitted_gmt', true );
		$ip_hash   = (string) get_post_meta( $post->ID, '_hk9_ip_hash', true );

		echo '<dl class="hk9-submission__meta">';
		echo '<dt>' . esc_html__( 'Form', 'heartland-k9s-core' ) . '</dt><dd>' . esc_html( $form ? $form->label() : $form_id ) . '</dd>';
		echo '<dt>' . esc_html__( 'Submitted', 'heartland-k9s-core' ) . '</dt><dd>' . esc_html( '' !== $submitted ? get_date_from_gmt( $submitted, get_option( 'date_format' ) . ' ' . get_option( 'time_format' ) ) : '' ) . '</dd>';
		echo '<dt>' . esc_html__( 'Email notification', 'heartland-k9s-core' ) . '</dt><dd>' . self::mail_badge( $sent ) . '</dd>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- escaped in helper.
		if ( $form ) {
			echo '<dt>' . esc_html__( 'Recipients', 'heartland-k9s-core' ) . '</dt><dd>' . esc_html( implode( ', ', $form->recipients() ) ) . '</dd>';
		}
		if ( $source > 0 ) {
			echo '<dt>' . esc_html__( 'Source page', 'heartland-k9s-core' ) . '</dt><dd><a href="' . esc_url( (string) get_permalink( $source ) ) . '">' . esc_html( get_the_title( $source ) ) . '</a></dd>';
		}
		echo '<dt>' . esc_html__( 'Sender hash', 'heartland-k9s-core' ) . '</dt><dd><code>' . esc_html( '' !== $ip_hash ? substr( $ip_hash, 0, 12 ) : '—' ) . '</code></dd>';
		echo '</dl>';
		echo '<p class="hk9-submission__actions"><a class="button-link-delete" href="' . esc_url( (string) get_delete_post_link( $post->ID ) ) . '">' . esc_html__( 'Move to Trash', 'heartland-k9s-core' ) . '</a></p>';
	}

	private static function mail_badge( bool $sent ): string {
		return $sent
			? '<span class="hk9-badge hk9-badge--ok"><span class="dashicons dashicons-yes" aria-hidden="true"></span> ' . esc_html__( 'Sent', 'heartland-k9s-core' ) . '</span>'
			: '<span class="hk9-badge hk9-badge--fail"><span class="dashicons dashicons-warning" aria-hidden="true"></span> ' . esc_html__( 'Not sent', 'heartland-k9s-core' ) . '</span>';
	}

	public static function columns( array $columns ): array {
		return [
			'cb'        => $columns['cb'] ?? '<input type="checkbox" />',
			'title'     => __( 'Submission', 'heartland-k9s-core' ),
			'hk9_form'  => __( 'Form', 'heartland-k9s-core' ),
			'hk9_name'  => __( 'Name', 'heartland-k9s-core' ),
			'hk9_email' => __( 'Email', 'heartland-k9s-core' ),
			'date'      => __( 'Date', 'heartland-k9s-core' ),
			'hk9_mail'  => __( 'Mail sent', 'heartland-k9s-core' ),
		];
	}

	public static function column_content( string $column, int $post_id ): void {
		switch ( $column ) {
			case 'hk9_form':
				$form = Handler::form( (string) get_post_meta( $post_id, '_hk9_form', true ) );
				echo esc_html( $form ? $form->label() : (string) get_post_meta( $post_id, '_hk9_form', true ) );
				break;
			case 'hk9_name':
			case 'hk9_email':
				$fields = get_post_meta( $post_id, '_hk9_fields', true );
				$fields = is_array( $fields ) ? $fields : [];
				if ( 'hk9_name' === $column ) {
					echo esc_html( trim( (string) ( $fields['first_name'] ?? '' ) . ' ' . (string) ( $fields['last_name'] ?? '' ) ) );
				} else {
					$email = (string) ( $fields['email'] ?? '' );
					echo is_email( $email ) ? '<a href="' . esc_url( 'mailto:' . $email ) . '">' . esc_html( $email ) . '</a>' : esc_html( $email );
				}
				break;
			case 'hk9_mail':
				echo self::mail_badge( (bool) get_post_meta( $post_id, '_hk9_mail_sent', true ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- escaped in helper.
				break;
		}
	}

	public static function row_actions( array $actions, \WP_Post $post ): array {
		if ( self::POST_TYPE !== $post->post_type ) {
			return $actions;
		}
		unset( $actions['inline hide-if-no-js'], $actions['view'] );
		if ( isset( $actions['edit'] ) ) {
			$actions['edit'] = '<a href="' . esc_url( (string) get_edit_post_link( $post->ID ) ) . '">' . esc_html__( 'View', 'heartland-k9s-core' ) . '</a>';
		}
		return $actions;
	}

	public static function bulk_actions( array $actions ): array {
		unset( $actions['edit'] );
		return $actions;
	}

	public static function filter_dropdown( string $post_type ): void {
		if ( self::POST_TYPE !== $post_type ) {
			return;
		}
		$current = isset( $_GET['hk9_form'] ) ? sanitize_key( wp_unslash( $_GET['hk9_form'] ) ) : ''; // phpcs:ignore WordPress.Security.NonceVerification.Recommended -- read-only list filter.
		echo '<label class="screen-reader-text" for="hk9-filter-form">' . esc_html__( 'Filter by form', 'heartland-k9s-core' ) . '</label>';
		echo '<select name="hk9_form" id="hk9-filter-form">';
		echo '<option value="">' . esc_html__( 'All forms', 'heartland-k9s-core' ) . '</option>';
		foreach ( Handler::forms() as $id => $form ) {
			echo '<option value="' . esc_attr( $id ) . '"' . selected( $current, $id, false ) . '>' . esc_html( $form->label() ) . '</option>';
		}
		echo '</select>';
	}

	public static function apply_filter( \WP_Query $query ): void {
		if ( ! is_admin() || ! $query->is_main_query() || self::POST_TYPE !== $query->get( 'post_type' ) ) {
			return;
		}
		$form = isset( $_GET['hk9_form'] ) ? sanitize_key( wp_unslash( $_GET['hk9_form'] ) ) : ''; // phpcs:ignore WordPress.Security.NonceVerification.Recommended -- read-only list filter.
		if ( '' !== $form && Handler::form( $form ) ) {
			$query->set(
				'meta_query',
				[
					[
						'key'   => '_hk9_form',
						'value' => $form,
					],
				]
			);
		}
	}

	public static function title_placeholder( string $placeholder, \WP_Post $post ): string {
		return self::POST_TYPE === $post->post_type ? '' : $placeholder;
	}

	public static function updated_messages( array $messages ): array {
		$messages[ self::POST_TYPE ] = array_fill( 0, 11, __( 'Submissions are read-only.', 'heartland-k9s-core' ) );
		return $messages;
	}
}
