#!/usr/bin/env node
/**
 * Compile the theme's Sass entries to assets/dist.
 *
 *   node tools/build-css.mjs            # one-off build
 *   node tools/build-css.mjs --watch    # rebuild on change
 *
 * Entries:
 *   assets/src/scss/theme.scss  -> assets/dist/theme.css   (frontend, compressed)
 *   assets/src/scss/editor.scss -> assets/dist/editor.css  (block editor styles, compressed)
 *
 * The `_fonts.scss` partial is generated by tools/fonts/build-fonts.py. When it is
 * missing (fresh checkout before fonts are built) a custom importer serves an empty
 * stylesheet for `@use 'fonts'` so the build never breaks; the theme then falls back
 * to the system font stacks declared in _tokens.scss.
 */

import { compile } from 'sass';
import { existsSync, mkdirSync, statSync, writeFileSync, watch } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const themeDir = resolve(root, 'theme/heartland-k9s');
const srcDir = resolve(themeDir, 'assets/src/scss');
const distDir = resolve(themeDir, 'assets/dist');

const entries = [
	{ in: resolve(srcDir, 'theme.scss'), out: resolve(distDir, 'theme.css') },
	{ in: resolve(srcDir, 'editor.scss'), out: resolve(distDir, 'editor.css') },
];

/** Optional partials: when the file is absent the importer returns an empty stylesheet. */
const optionalPartials = new Set(['fonts']);

const optionalImporter = {
	canonicalize(url) {
		const name = url.replace(/^hk9-optional:/, '');
		if (!optionalPartials.has(name)) {
			return null;
		}
		const candidates = [
			resolve(srcDir, `_${name}.scss`),
			resolve(srcDir, `${name}.scss`),
		];
		const found = candidates.find((f) => existsSync(f));
		if (found) {
			return pathToFileURL(found);
		}
		return new URL(`hk9-optional:${name}`);
	},
	load(canonicalUrl) {
		if (canonicalUrl.protocol !== 'hk9-optional:') {
			return null;
		}
		process.stderr.write(`[build-css] optional partial "${canonicalUrl.pathname}" is missing — using an empty fallback.\n`);
		return { contents: '', syntax: 'scss' };
	},
};

function build() {
	mkdirSync(distDir, { recursive: true });
	let ok = true;
	for (const entry of entries) {
		if (!existsSync(entry.in)) {
			process.stderr.write(`[build-css] entry missing: ${entry.in}\n`);
			ok = false;
			continue;
		}
		try {
			const result = compile(entry.in, {
				style: 'compressed',
				loadPaths: [resolve(root, 'node_modules'), srcDir],
				importers: [optionalImporter],
				quietDeps: true,
				silenceDeprecations: ['import', 'global-builtin', 'color-functions', 'if-function'],
				sourceMap: false,
			});
			writeFileSync(entry.out, result.css + '\n');
			const size = statSync(entry.out).size;
			process.stdout.write(`[build-css] ${entry.out.replace(root + '/', '')}  ${(size / 1024).toFixed(1)} kB\n`);
		} catch (err) {
			ok = false;
			process.stderr.write(`[build-css] FAILED ${entry.in}\n${err.message}\n`);
		}
	}
	return ok;
}

const ok = build();

if (process.argv.includes('--watch')) {
	let timer = null;
	watch(srcDir, { recursive: true }, () => {
		clearTimeout(timer);
		timer = setTimeout(build, 80);
	});
	process.stdout.write('[build-css] watching for changes…\n');
} else if (!ok) {
	process.exit(1);
}
